version: '3.8'
services:
  registry-discovery:
    container_name: id-eureka
    image: "eureka:0.0.1-SNAPSHOT"
    ports:
      - 8761:8761
    environment:
      - JAVA_OPTS=
        -Xms256M
        -Xmx256M

  configuration:
    container_name: id-config
    image: "configserver:0.0.1-SNAPSHOT"
    volumes:
    # retrocede 2 carpetas y se mete a la carpeta de configuracion
      - ../../config-server-microservicios:/tmp/config-server-repo
    environment:
      - JAVA_OPTS=
        -Xms256M
        -Xmx256M
        -DEUREKA_SERVER=http://registry-discovery:8761/eureka/
        -DLOCAL_REPOSITORY=/tmp/config-server-repo
    depends_on:
      - registry-discovery
    ports:
      - 8888:8888
  administration:
    container_name: id-admin
    image: "adminserver:0.0.1-SNAPSHOT"
    environment:
      - JAVA_OPTS=
        -Xms256M
        -Xmx256M
        -DEUREKA_SERVER=http://registry-discovery:8761/eureka/
    depends_on:
      - registry-discovery
    ports:
      - 8762:8762
  product-catalog:
    container_name: bd-product-catalog
    image: "product:0.0.1-SNAPSHOT"
    environment:
      - JAVA_OPTS=
        -Xms256M
        -Xmx256M
        -DEUREKA_SERVER=http://registry-discovery:8761/eureka/
    depends_on:
      - registry-discovery
      - configuration
    ports:
      - 8083:8083
  customer:
    container_name: bd-customer
    image: "customer:0.0.1-SNAPSHOT"
    environment:
      - JAVA_OPTS=
        -Xms256M
        -Xmx256M
        -DEUREKA_SERVER=http://registry-discovery:8761/eureka/
        -Dspring.profiles.active=development
    depends_on:
      - registry-discovery
      - configuration
    ports:
      - 8081:8081

  transactions:
    container_name: bd-transactions
    image: "transactions:0.0.1-SNAPSHOT"
    environment:
      - JAVA_OPTS=
        -Xms256M
        -Xmx256M
        -DEUREKA_SERVER=http://registry-discovery:8761/eureka/
        -Dspring.profiles.active=development
    depends_on:
      - registry-discovery
      - configuration
    ports:
      - 8082:8082
  postgres_db:
    container_name: postgres
    image: postgres:latest
    ports:
      - 3432:5432
    volumes:
      - ./dbfiles:/docker-entrypoint-initdb.d
      - /var/lib/postgresql/data
    environment:
      - POSTGRES_USER: postgres
      - POSTGRES_PASSWORD: 1234
      - POSTGRES_DB: postgres
  pgadmin4:
    image: dpage/pgadmin4
    restart : always
    environment:
      - PGADMIN_DEFAULT_EMAIL: "admin@admin.com"


     